### ISSUE TITLE
Set new schedule

### ISSUE THREAD

**Issue by ggham** [freeuni-sdp/iot-sprinkler-scheduler#3]
მგონი Set new schedule-ს დროს excluded ლისტში რაც იყო ადრე მაინც რჩება, და ახალი რაც გავგზავნე ეგენიც ემატება.

**Comment by chalagashvili** [comment]
ახალ Schedule-ს ქმნი რომელსაც excluded-ცარიელი აქვს, მერე შენ ამატებ ელემენტებს და მასე გადასცემ და ძველები მაინცაა?

**Comment by ggham** [comment]
ახლა დავაკვირდი და სხვა პრობლემაა. http://docs.sprinklerscheduler.apiary.io/#reference/0/schedule/get-current-schedule?console=1
აი აქ რესურსის ქოლი სცადე რამდენჯერმე ზედიზედ რამდენიმე წამიანი შუალედებით, და ყოველ ახალ დაბრუნებაზე ერთ ენთრის ამატებს excluded ლისტში. სახლის აიდი ეს არის: 3db0d8b8-b664-4152-892d-2434e7216643

**Comment by ggham** [comment]
მგონი არარის სქედულერის ბრალი,  სავარაუდოდ სიმულატორი პოსტავს ხშირად ერთიდაიგივე დღის ჩამატებას. დავხურავ იშუს.
